[IV-24-25] GitIgnore añadido
Mario25402/AskETSIIT pull request #2
Opened 2024-09-20 12:04 UTC by Mario25402

Reverts Mario25402/Calendar#1

2024-09-22 10:30 UTC, JJ commented
Lo que se busca con los PRs es que se pueda ver desde el profesor, en la pestaña "files", cuales han sido los cambios. Como puedes comprobar, aquí no se puede ver nada. Por otro lado, [seguir la lista de comprobación](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#lista-de-comprobaci%C3%B3n) te ayudará a ver si has entendido correctamente lo que se requiere en este objetivo.

2024-09-23 09:51 UTC, Mario25402 commented
* [ x ] ¿Se trata de un problema real del que se tenga conocimiento personal?

* [ x ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
** Ayudará a mantener la aplicación y podrá ser usada por varios participantes, al igual que añadir abstacción y seguridad al proyecto.

* [ x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
** Requiere organización y procesamiento, no solo almacenado y busqueda.

* [ x ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

* [ x ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
** Es posible el desarrollo a partir de los datos iniciales.

* [ x ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?

2024-09-23 15:29 UTC, JJ commented
> * [ x ] ¿Se trata de un problema real del que se tenga conocimiento personal?
> 
>     * [ x ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
>       ** Ayudará a mantener la aplicación y podrá ser usada por varios participantes, al igual que añadir abstacción y seguridad al proyecto.
> 
>     * [ x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
>       ** Requiere organización y procesamiento, no solo almacenado y busqueda.
> 
>     * [ x ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
> 
>     * [ x ] ¿Tienes todos los datos necesarios para poder resolver el problema, o vas a requerir que el usuario los introduzca?
>       ** Es posible el desarrollo a partir de los datos iniciales.
> 
>     * [ x ] ¿Has seguido la lista de comprobación o estás marcando al buen tuntún todo?

¿Cuál de los dos? ¿Lo has seguido o lo has marcado al buen tuntún?

Por otro lado, es en el cuerpo del PR, no en un comentario.

2024-09-24 07:36 UTC, Mario25402 commented
corregido, imagino que el cuerpo del PR en este caso es la primera caja de comentarios.

2024-09-24 08:23 UTC, JJ requested changes
Me temo que el problema no está suficientemente bien definido. ¿Esto fue lo que salió del juego de design thinking?

2024-09-24 08:24 UTC, JJ commented
> * [ x ] ¿Se trata de un problema real del que se tenga conocimiento personal?
> * [ x ] ¿Se trata de un problema que para solucionar requiera el despliegue de una aplicación en la nube?
>   ** Ayudará a mantener la aplicación y podrá ser usada por varios participantes, al igual que añadir abstacción y seguridad al proyecto.
> * [ x ] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez solucionarse sólo almacenando y buscando?
>   ** Requiere organización y procesamiento, no solo almacenado y busqueda.
> * [ x ] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?

¿Por qué has marcado esto?

2024-09-24 17:55 UTC, Mario25402 commented
Listo para revisión

2024-09-24 18:02 UTC, JJ requested changes
Por un lado, parece que la configuración la has enlazado correctamente, aunque ni el .gitignore ni el LICENSE forman parte de la misma y no sé por qué todo el mundo cree que es así.
Si este es el problema validado, deberías comenzar de nuevo; si no lo es, conviene que transcribas lo escrito. En cualquiera de los casos tienes que tener en cuenta que debe ser un documento para iniciar un proceso de desarrollo de una aplicación desplegable en la nube, no una respuesta individual a un ejercicio o una "práctica".

2024-09-24 18:02 UTC, JJ commented on README.md
>  Soy una persona ocupada y despistada, tengo muchos eventos en los que debo tener atención y actividades de los eventos por realizar, necesito organizarme y poner atención a lo que es posible realizar
El problema es muy ambiguo y está mal definido. La única necesidad que expresa es "poner atención". No veo claro que sea un problema que se pueda abordar desde una aplicación. En general, la descripción del problema es insuficiente para iniciar un proceso de desarrollo de una aplicación, en la nube o no.

2024-09-26 18:56 UTC, Mario25402 commented
Problema actualizado.

2024-09-27 05:39 UTC, JJ requested changes
La metodología *design thinking*, llevada a cabo a través del juego que hicimos o por cuenta de uno, es una de las metodologías que te ayudan a entender al cliente y definir un problema, trata de evitar pasar de un problema poco definido ("problemas de inventario") a soluciones que aporten poco valor (almacenar las fechas del stock y recuperarlas).
Como en todos los objetivos de la asignatura y en general, conviene que entiendas la metodología y la apliques. Con ello te ahorrarás envíos repetidos con problemas mal formulados (o sin formular) o con soluciones sin mucho valor añadido.

2024-09-27 05:39 UTC, JJ commented on README.md
> +Las personas que se dedican a la agricultura del aceite normalmente se agrupan en cooperativas lo que hace que la gestión sea complicada debido a la cantidad de personas pertenecientes a la misma. Un
¿El problema involucra algo más que el almacenamiento y recuperación?

Del [guión](http://jj.github.io/IV/documentos/proyecto/0.Repositorio#descripci%C3%B3n):

> Si la idea y la descripción del problema sólo incluye palabras como “almacenamiento” y “búsqueda”, mientras que puede ser una aplicación completa perfectamente válida (dotada de un interfaz de usuario adecuado), los diferentes pasos por los que pasará la resolución del problema en los siguientes objetivos no van a dar mucho de sí. Es decir, si se trata simplemente de objetos con un ciclo CRUD (create, read, update y delete), descártala y piensa en otra que sí realice algún tipo de procesamiento.

2024-09-27 11:08 UTC, Mario25402 commented on README.md
> +Las personas que se dedican a la agricultura del aceite normalmente se agrupan en cooperativas lo que hace que la gestión sea complicada debido a la cantidad de personas pertenecientes a la misma. Un
Sí, la idea es analizar las tendencias del mercado para ofrecer sugerencias de venta, es decir, qué mensualidades o épocas son las que más conviene tener stock, de la misma manera, ver que configuración de los diferentes productos (envases de diferentes litros) es la más exitosa para aplicar enfásis en la producción de la misma.

2024-09-27 12:21 UTC, Mario25402 commented
Reescrito

2024-09-27 18:22 UTC, JJ requested changes
¿De veras crees que lo que describes aquí se puede hacer como un proyecto de la asignatura?
Por favor, tratad de definir bien el problema y comprobar que efectivamente sea algo que podáis abordar con las restricciones que impone esta asignatura.

2024-09-27 18:22 UTC, JJ commented on README.md
> +Las personas que se dedican a la agricultura del aceite normalmente se agrupan en cooperativas lo que hace que la gestión sea complicada debido a la cantidad de personas pertenecientes a la misma ya
sobre todo va separado.

2024-09-27 18:22 UTC, JJ commented on README.md
> +La gestión eficiente del inventario en tiempo real y la predicción de picos de demanda se han convertido en los desafíos clave. Se necesita una solución que:
En general, no debes describir la solución. Deberías más bien describir los datos que se tienen, más que los que se quieren. Si no sabes qué datos se tienen, es imposible que una persona que reciba este documento trate de solucionarlo.

Recuerda además que toda la lógica de negocio tienes que hacerla tú, es decir, tendrás que escribir tú el algoritmo de predicción, y *probar que hace esa predicción*. Si el problema es predecir, tienes que *probar* que tu algoritmo resuelve el problema.

2024-09-27 18:22 UTC, JJ commented on README.md
> +* Proporcione visibilidad en tiempo real sobre la disponibilidad de productos en las diferentes estaciones de la cooperativa.
Una vez más, estás hablando de soluciones. Esto no me proporciona contexto para entender mejor el problema, ni parece que ayude a predecir los picos de demanda. Y "visibilidad en tiempo real" no deja de ser un problema CRUD sin lógica de negocio aparejada.

2024-09-27 18:22 UTC, JJ commented on README.md
> +* Integre una lógica de negocio avanzada que permita la predicción de demanda en función de las tendencias de compra y los comportamientos de los consumidores.
Esa lógica de negocio avanzada, ¿es la que vas a programar para el objetivo 4?

2024-10-01 16:36 UTC, Mario25402 commented
He modificado el proyecto para que se centre en un solo problema descrito claramente.

2024-10-01 18:29 UTC, JJ requested changes
Si no se sigue la metodología sugerida en este caso, design thinking, o cualquier otra, es muy complicado llegar a una descripción de problema que pueda resultar una base para empezar a trabajar. La metodología te permite entender un problema; el guión te restrinje los problemas posibles a aquellos que se puedan abordar en la asignatura. Pero sin encontrar un problema y describirlo bien, no se puede ni siquiera plantear si se puede abordar en la asignatura o no.
Por favor, trata de entender qué es lo que se busca en este objetivo, pero sobre todo, por qué y plantea un problema que te pueda servir el resto de la asignatura. Si tiene que estar relacionado con el aceite, mira a ver si hubiera alguna fuente de datos poco estructurados que se pudiera procesar para resolver algún problema, o consulta los portales de datos abiertos sugeridos por si hubiera algún dato poco estructurado que haya que procesar y validar, o datos que se puedan procesar de alguna forma no trivial para crear una lógica de negocio.

2024-10-01 18:29 UTC, JJ commented on README.md
> +Los productores de aceite de una coperativa tienen problemas para dotar de suministros a todas sus estaciones por falta de supervisión.
¿Realmente crees que con esta descripción se puede empezar a desarrollar una aplicación?
Lee también [el fichero de errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido):

> Un problema no se puede empezar a describir como el problema de. Si quieres realmente describir un problema de forma que puedas abordarlo en la asignatura, tendrías que empezar a preguntar a ese cliente (o a ti mismo) por qué tienen ese problema. De esa forma podrás acercarta un poco más a describir el problema de forma que se pueda resolver en la asignatura.

2024-10-02 16:19 UTC, Mario25402 commented
Corregido y cambiado a un problema más sugerente para la asignatura

2024-10-02 16:30 UTC, JJ requested changes
Por favor, quitad de una vez el .gitignore y LICENSE. Si no lo habéis creado al crear el repositorio, mal, pero no forma parte de nada que tenga que corregirse, es sólo imprescindible para pasar los tests y lo único qu ese comprueba es la existencia. Si es que lo habéis añadido ahora en el PR, no pasa nada, pero  por favor tenedlo en cuenta para PRs futuros que sólo hay que añadir al PR aquello que se tenga que corregir.

Por otro lado, te recuerdo que has marcado en la check list estos dos items:

> ¿La solución requiere una cierta cantidad de lógica de negocio, en vez de solucionarse sólo almacenando y buscando?

Has respondido:

> Sí, se necestita de un sistema más complejo de categorización que facilite la busqueda eficiente.

¿Dónde está la categorización en el problema descrito? Aunque fuera necesaria la categorización, la solución es literalmente *buscar*. En [el guión](https://jj.github.io/IV/documentos/proyecto/0.Repositorio) dice que no se deben incluir en la descripción de la solución al problema (sólo necesaria si no está claro por la descripción del problema la necesidad de una lógica de negocio compleja)

> No incluir palabras como “buscar”, “dar de alta”, “poner en contacto”, “recuperar”, “integrar”, “alertar”, “comunicar”.

Si esto corresponde a lo que conté por el grupo de Telegram, habría sido conveniente que, siguiendo la metodología de *design thinking*, hubieras preguntado a alguien que tenga ese problema por qué es un problema y qué aspecto tiene el problema, en vez de sugerir una solución que, de todas formas, no se adecúa ni soluciona el problema.

2024-10-02 17:39 UTC, Mario25402 commented
Remodelación completada

2024-10-02 17:55 UTC, Mario25402 commented
Sí se encuentran en el main

2024-10-02 17:57 UTC, JJ commented
:+1: 

(No debías haberlos puesto aquí, entonces)

2024-10-03 07:00 UTC, merged