[IV-24-25] Objetivo 2
Mario25402/AskETSIIT pull request #21
Opened 2024-11-22 15:10 UTC by eigenric

**Lista de comprobación para quien desarrolle el objetivo**

**Sobre la estructura del repositorio**

* [x] ¿He seguido las mejores prácticas en el nombre de las clases y ficheros y disposición de los mismos?
Se han creado los modelos en una carpeta internal que permite no exponerlos (por importación) fuera del paquete original.
* [x] ¿He mirado tanto reglas generales (para cualquier repo) como reglas específicas para el lenguaje con el que se está trabajando?
Go tiene además un fichero go.mod donde se indica la versión así como una serie de ficheros que deberían ser ignorados por git. (ver .gitignore)

**Sobre el planteamiento**

* [x] ¿Se han planteado una serie de issues, asignados a las historias de usuario pertinentes, que clarifiquen qué es lo que necesitan los usuarios e identifiquen las diferentes partes del problema?
Se han creado en cascada los issues #13, #14, #15, #16, #17,  #19, #20

* [x] ¿Los issues representan un problema, y no una tarea?
Sí, el problema consiste representar mediante código en Go las entidades y sus atributos (modelado).

**Sobre el análisis del problema**

* [x] ¿Se ha documentado qué análisis se ha hecho sobre el dominio para decir lo que se ha creado?
 Sí, se ha creado un issue especifico #12 para analizar las estructuras y las restricciones asociadas.

* [x] ¿Se ha documentado por qué se ha elegido que lo creado sea un objeto valor, una entidad o un agregado?

Sí, en cada caso, se distingue la entidad cuando implica que su identidad cambia cuando se cambian ciertos elementos, o los objetos valor cuando expresan estado para cómputo.

* [x]  ¿He propuesto un producto mínimamente viable, que en muchos casos será un solo objeto valor que no dependa de ningún otro (y que sea la base de muchos otros)?
El producto mínimamente viable consiste en el modelado de la entidad Horario de la dependen el resto.

**Sobre el código**

* [x]  ¿Todos los mensajes de commit explican el cambio, y no se limitan a repetir el nombre del fichero que se ha cambiado?
La mayoría de mensajes de commit tienen cuerpo 

* [x] ¿Los mensajes de commit siguen el formato estándar y buenas prácticas?
No se añade información innecesaria.

* [x]  ¿Se ha hecho una revisión real del código para comprobar que todos los atributos y funciones creadas están respaldadas por una HU?
Cada fragmento de código pretende resolver un issue,

* [x] ¿Todos los issues creados están relacionados con a una HU?
 Todos los issues están asociado a la HU1. Hay dependencia en cascada entre los issues.

* [x]  ¿Ha asignado el propietario/la propietaria del repositorio todos los issues planteados al milestone correspondiente?
Sí
* [x] ¿Todos los cambios en el código están asignados a un issue al que se referencia en un commit?
Sí
* [x]  ¿Se ha asignado al mismo milestone el PR que se ha hecho?
Sí
* [x] ¿Es el milestone sobre el que estoy trabajando un producto mínimamente viable? ¿O tengo que solicitar al product manager que precise de qué producto se trata?
Se pretende alcanzar el Milestone 0 de PMV.
* [x]  ¿Se ha comprobado que el código entregado sea sintácticamente correcto?
Sí

2024-11-22 15:24 UTC, eigenric commented
Debido a [este bug](https://github.com/orgs/community/discussions/78775) de Github he tenido que rehacer el PR. He resuelto los comentarios que se me señalaron: 

* [x] De acuerdo a la actualización de la [HU1](https://github.com/Mario25402/AskETSIIT/issues/4) , ahora el correo del profesor no es necesario, por lo que basta un string para representar su nombre
* [x] Una entidad horario y una función para agregar clases que valide solapamiento no forma parte del modelado sino que se considera lógica de negocio.
* [x] El fichero iv.yaml señala al fichero de entidad clase.go

2024-11-22 16:31 UTC, Mario25402 approved these changes

2024-11-25 16:15 UTC, JJ requested changes
Por otro lado, el issue #19 no está ligado a ninguna historia de usuario y tampoco asignado a ningún milestone, luego cualquier código que se desarrolle a partir de él es incorrecto.

2024-11-25 16:15 UTC, JJ commented on internal/diasemana/diasemana.go
Como dice aquí: [028c13e](https://github.com/Mario25402/AskETSIIT/commit/028c13e933634fd31448b1b5ff0577bb78516d4a) 

```
Se opta por usar 5 constantes a las que se asigna
una representación por string.
```

no estás discutiendo diferentes opciones, simplemente enunciando lo que has hecho, que ya se puede ver perfectamente en el código. Es imposible saber qué alternativas has considerado.

2024-11-25 20:47 UTC, eigenric commented
Cierto. Ahora #19 #20 están asignados a [[M0](https://github.com/Mario25402/AskETSIIT/milestone/1)] y por tanto ligados a la [HU1](https://github.com/Mario25402/AskETSIIT/issues/4).  En lo siguiente incluiré en el cuerpo de commit las alternativas de representación de día de la semana.

2024-11-27 10:22 UTC, Mario25402 approved these changes
Cuando puedas corrige el comentario de #15.

2024-11-28 11:40 UTC, eigenric commented
Listo para revisión @JJ

2024-11-28 12:44 UTC, JJ commented on internal/models/periodo.go
> +func NuevoPeriodo(horaInicioStr, horaFinStr string) (*Periodo, error) {
¿`Nuevo` es la forma estándar de la función para crear un nuevo objeto en Golang?

2024-11-28 12:52 UTC, JJ reviewed
Por favor, dale una vuelta a lo que hemos hablado.

2024-12-08 20:27 UTC, evaanngiil requested changes
Buenas, se me ha asignado revisar tu PR. Aparte de lo comentado por JJ. Tengo dudas acerca si estas en camino de resolver todos los issues planteados. En #13 se plantea como representar un horario, sin embargo, se ha eliminado la clase. ¿Entonces como se gestionan las clases de cada alumno? Además, ¿crees que la representación de un alumno podría añadir algo a la lógica de negocio?

2024-12-08 20:27 UTC, evaanngiil commented on internal/models/clase.go
> +}
¿Quién gestiona las clases exactamente? ¿Es un objeto valor o una entidad??

2024-12-10 13:24 UTC, eigenric commented on internal/models/clase.go
> +}
Es un objeto valor, sin embargo se rechazó la entidad horario (como gestora de clases) en el antiguo pull request por no formar parte del modelado.

2024-12-10 13:24 UTC, eigenric commented
@evaanngiil En efecto en [977505a](https://github.com/Mario25402/AskETSIIT/pull/21/commits/977505ab6e3262512a5339c6db309b2375b4de47) , se eliminó el horario como parte del modelado, entiendo que por incluir funciones que eran parte de la lógica de negocio (validación de solapamiento de clases). Sin embargo el horario es lo que constituye la entidad formada por una secuencia de clases, y se volvió a reconsiderar su inclusión (sin las funciones) en la conversación con @JJ.
En cuanto al estudiante, se discutió con @Mario25402 , y se concluyó no representarlo en el modelado, es decir, sólo se gestiona el horario del estudiante que utiliza la aplicación.

2024-12-10 17:04 UTC, evaanngiil commented
En el caso que me mencionas @eigenric ¿quién gestionaría las `Clases`?

2024-12-12 12:00 UTC, eigenric commented
El estudiante gestionaría las clases. Sin embargo, no se ha considerado modelarlo en la conversación con @Mario25402 para que la aplicación sea más impersonal y no guarde información del usuario. Además, como el horario está en relación 1-1 con estudiante, se considera esta como la entidad fundamental.

2024-12-12 12:04 UTC, eigenric commented
Listo para revisión @JJ

2024-12-12 12:21 UTC, JJ requested changes
El concepto más importante del objetivo dos es el de SSOT; conviene que entendáis las estructuras de datos que lo garantizan.

2024-12-12 12:21 UTC, JJ commented on internal/diasemana/diasemana.go
> +	Lunes DiaSemana = iota
Si esto vas a imprimirlo, ¿es la mejor forma de trabajar con él con un número?

2024-12-12 12:21 UTC, JJ commented on internal/models/horario.go
> +	Clases []Clase
Tienes que garantizar una única fuente de verdad para cada clase.

2024-12-12 19:45 UTC, eigenric commented
Se han corregido los siguientes problemas:

* [x] Ahora DíaSemana es un enum de strings como anteriormente
* [x] Periodo tiene dos estados para cada hora: "En punto" e "Y media" representados por otro enum (constantes). Esto ha permitido además eliminar código redundante
* [x] El Horario es la entidad fundamental, SSOT, que esta vez se ha represntado mediante un doble Map (diccionario) con primera clave el dia de la semana y segunda la HoraMinuto, y el valor la clase. Esto permite lanzar un error si se construye un horario donde dos clases empiezan el mismo día a la misma hora.

Se ha comprobado el buen funcionamiento del modelo con un `main.go` de ejemplo.

2024-12-13 11:42 UTC, Mario25402 approved these changes
Entiendo al punto al que has llegado, considero que un diccionario como el tipo de `Horario` es una buena opción para evitar solapamientos y tambień las simplificaciones sobre el periodo y los dias.

2024-12-13 11:45 UTC, eigenric commented
Listo para revisión @JJ

2024-12-13 13:21 UTC, JJ approved these changes
👍

2024-12-13 13:21 UTC, JJ commented on internal/models/horario.go
> +		// Inicializa el diccionario para el día si no existe
No dejéis comentarios inline en el código

2024-12-13 13:21 UTC, JJ commented on internal/models/horario.go
> +		// Verifica si ya existe una clase en el horario de inicio
Igual

2024-12-13 13:21 UTC, JJ commented on internal/models/horario.go
> +		// Agrega la clase al horario
Y ya estás metiendo demasiada lógica para un modelo, pero en fin...

2024-12-13 13:27 UTC, merged