[IV-24-25] Objetivo 3
Mario25402/AskETSIIT pull request #24
Opened 2024-12-02 12:23 UTC by Mario25402

* [x] ¿Incluye el fichero `iv.yaml` las claves de todos los objetivos
anteriores?
* [x] ¿Se ha desarrollado el fichero para las tareas a partir de un
   issue?
* [x] ¿Ese issue está asignado a un milestone?
* [x] ¿El milestone incluye, entre sus productos mínimamente viables, la
  existencia de herramientas que permitan automatizar tareas?
* [x] ¿Hemos justificado correctamente en caso de elegir un gestor de
   dependencias el que se use como gestor de tareas?
* [x] ¿El PR, que también es un issue, está asignado al mismo milestone?
* [x] ¿La tarea `check` efectivamente comprueba la sintaxis de los fuentes
  existentes y sólo eso?
* [x] ¿Se ha comprobado que las instrucciones incluidas en el `README.md` son
completas y correctas?

2024-12-02 16:41 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +- Versatilidad e integración con el lenguaje.
Como se establece en en los errores comunes del objetivo:
_Una vez que se corrige el objetivo anterior, usar criterios arbitrarios que sean verdad sólo para la herramienta que hemos elegido de antemano. Por ejemplo "Compatibilidad con el lenguaje". ¿Hay algún gestor de tareas que sea incompatible con algún lenguaje?_

2024-12-02 16:41 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +- Seguridad y velocidad.
Lo mismo con este al menos que te pongas a probar de forma empírica estos dos criterios podrían tratarse de criterios arbitrarios

2024-12-02 16:41 UTC, juanbarearojo commented on docs/gestor_dependencias.md
> +## Configuración manual
Es importante destacar que el uso de la carpeta "vendor" es una forma de incluir las dependencias en el proyecto, pero no actúa como un gestor de dependencias en sí mismo.

2024-12-02 16:41 UTC, juanbarearojo commented on docs/gestor_tareas.md
> +	- Versátil e ideal para proyectos multilenguaje.
Tienes pensado trabajar con varios lenguajes. Si no lo tienes pensado esto crea ruido en tus decisiones y puede hacer que que se ha puesto por rellenar.

2024-12-02 16:41 UTC, juanbarearojo commented on Taskfile.yml
> +      - go vet ./...
go vet hace mas cosas que solo comprobar la sintaxis

2024-12-02 17:45 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- Versatilidad e integración con el lenguaje.
No era a lo que me quería referir pero aun así lo he eliminado ya que veo que es ambiguo. https://github.com/Mario25402/AskETSIIT/commit/8f1cd4e405e97b442eb77e023c197bc6abb5a056

2024-12-02 17:46 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- Seguridad y velocidad.
https://github.com/Mario25402/AskETSIIT/commit/8f1cd4e405e97b442eb77e023c197bc6abb5a056

2024-12-02 17:49 UTC, Mario25402 commented on docs/gestor_dependencias.md
> +## Configuración manual
Correcto el rol de gestor lo toma la persona que hace esa tarea. https://github.com/Mario25402/AskETSIIT/commit/4f7597f53154e9386222bae5ec880ccecf244786

2024-12-02 17:51 UTC, Mario25402 commented on docs/gestor_tareas.md
> +	- Versátil e ideal para proyectos multilenguaje.
Hasta el punto en el que vamos a llegar no, pero como se comentó en clase, practicamente ningún proyecto se va a desarrollar en un solo lenguaje, si en un futuro se quisiera hacer, cosa que es probable, lo opción ya está contemplada.

2024-12-02 18:04 UTC, Mario25402 commented on Taskfile.yml
> +      - go vet ./...
Según tengo entendido, hay 3 opciones (no se si existen más):
- **go vet:** Analiza los archivos y detecta errores.
- **go fmt:** Verifica que se siguen los estándares de Go.
- **go build -n:** Verifica los archivos sin compilarlos y muestra los comandos a ejecutar.

Consideras más adecuado el uso de go fmt o hay alguna alternativa que no estoy considerando @juanbarearojo.

2024-12-02 21:45 UTC, MarioRgzLpz commented
Buenas se me ha asignado revisar esta PR. Añado algunas puntualizaciones a lo ya dicho por mi compañero.

2024-12-02 21:47 UTC, MarioRgzLpz commented on docs/gestor_tareas.md
> +- Características y funcionalidades.
Estos requisitos aunque validos, son algo escuetos. Estaría bien que desarrollaras un poco más cada criterio.

2024-12-02 21:50 UTC, MarioRgzLpz commented on docs/gestor_tareas.md
> +	- Deuda técnica baja ya que es intuitiva para desarrolladores familiarizados con Go.
¿Cómo puedes asegurar que tiene una deuda técnica baja siendo su última release de hace más de un año? Además tiene unos cuantos commits recientes y el resto de hace bastante tiempo.

2024-12-03 08:36 UTC, Mario25402 commented on docs/gestor_tareas.md
> +	- Deuda técnica baja ya que es intuitiva para desarrolladores familiarizados con Go.
Pues tienes razón, ni me había dado cuenta.

2024-12-03 09:07 UTC, juanbarearojo commented on Taskfile.yml
> +      - go vet ./...
Eso es una decisión que debes tomar tú pero no lo veo mas encaminado.

2024-12-03 17:05 UTC, Mario25402 commented on Taskfile.yml
> +      - go vet ./...
https://github.com/Mario25402/AskETSIIT/commit/163244865646954239cacc9fc10737976aca5c06

2024-12-03 17:19 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- Características y funcionalidades.
https://github.com/Mario25402/AskETSIIT/commit/564d7b39ad12a7dd8c5be6b75f7f8f17fdb2f89d

2024-12-05 07:47 UTC, MarioRgzLpz approved these changes

2024-12-05 08:09 UTC, Mario25402 commented
@JJ

2024-12-05 08:52 UTC, JJ reviewed
Por favor, trata de encontrar también alguna alternativa más, que la hay. Usa las herramientas comunes: Reddit, por ejemplo

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +- **Deuda técnica:** impacto que tiene una herramienta a lo largo del tiempo, en relación al aprendizaje, dificultad de  integración, uso, etc...
Para empezar, la deuda técnica no se puede medir. Se pueden medir cosas que causan deuda técnica o no. Pero para seguir es que la deuda técnica no es lo que dices que es.

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +- **Versatilidad:** capacidad para adaptarse a difentes proyectos, entornos y lenguajes.
Qué decirte de esto...

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +- **Soporte y comunidad activa:** versiones, recursos y documentación actualizada.
¿Cómo lo mides esto?

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +- **Características y funcionalidades:** rasgos y capacidades que diferencian una herramienta de otra.
¿Como lo mides esto también?

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +	- Es escalable gracias a su integración directa con el lenguaje.
¿Esto es una característica o criterio para elegir o no?

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +	- Rápida por no tener que interpretar archivos externos.
Esto no tiene nada que ver con la rapidez.

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +	- Útil con tareas de despliegue continuo.
¿Es un gestor de tareas?

2024-12-05 08:52 UTC, JJ commented on docs/gestor_tareas.md
> +	- Recomendado para proyectos que requieren gestión automatizada de lanzamientos.
Es decir, no para gestión de tareas.

2024-12-06 18:10 UTC, Mario25402 commented on docs/gestor_tareas.md
> +	- Es escalable gracias a su integración directa con el lenguaje.
https://github.com/Mario25402/AskETSIIT/commit/839135ed4dd635f8af667c95ac8bc3b8754a145d

2024-12-06 18:11 UTC, Mario25402 commented on docs/gestor_tareas.md
> +	- Útil con tareas de despliegue continuo.
https://github.com/Mario25402/AskETSIIT/commit/839135ed4dd635f8af667c95ac8bc3b8754a145d

2024-12-06 18:12 UTC, Mario25402 commented on docs/gestor_tareas.md
> +	- Recomendado para proyectos que requieren gestión automatizada de lanzamientos.
https://github.com/Mario25402/AskETSIIT/commit/839135ed4dd635f8af667c95ac8bc3b8754a145d

2024-12-06 18:14 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Características y funcionalidades:** rasgos y capacidades que diferencian una herramienta de otra.
https://github.com/Mario25402/AskETSIIT/commit/148f57616eb15ffcceb470cc78872e7bdce939ea

2024-12-06 18:14 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Deuda técnica:** impacto que tiene una herramienta a lo largo del tiempo, en relación al aprendizaje, dificultad de  integración, uso, etc...
https://github.com/Mario25402/AskETSIIT/commit/148f57616eb15ffcceb470cc78872e7bdce939ea

2024-12-06 18:14 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Versatilidad:** capacidad para adaptarse a difentes proyectos, entornos y lenguajes.
https://github.com/Mario25402/AskETSIIT/commit/148f57616eb15ffcceb470cc78872e7bdce939ea

2024-12-06 18:14 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Soporte y comunidad activa:** versiones, recursos y documentación actualizada.
https://github.com/Mario25402/AskETSIIT/commit/148f57616eb15ffcceb470cc78872e7bdce939ea

2024-12-06 18:15 UTC, Mario25402 commented
@JJ

2024-12-10 06:55 UTC, JJ requested changes
No continúo. Por favor, usa un lenguaje con la precisión adecuada para un documento técnico, que es de lo que se trata.

2024-12-10 06:55 UTC, JJ commented on Taskfile.yml
> +      - go fmt ./...
¿Estás seguro que esto solo comprueba la sintaxis?

2024-12-10 06:55 UTC, JJ commented on docs/gestor_dependencias.md
> +## Configuración manual
Lo que te está diciendo @juanbarearojo es que no incluyas información irrelevante. Yo también te lo agradecería.

2024-12-10 06:55 UTC, JJ commented on docs/gestor_tareas.md
> +- **Madurez y robustez:** El nivel de desarrollo de la herramienta debe ser suficiente y debe seguir teniendo mantenimiento frecuente para maximizar la compatibilidad con el lenguaje y minimizar los
¿Qué tiene que ver eso con la robustez? ¿Esto son dos criterios o uno solo?

2024-12-10 06:55 UTC, JJ commented on docs/gestor_tareas.md
> +- **Adición de complejidad:** Se valorará la simplicidad de inclusión y uso del gestor, de manera que no aumente la dificultad del proyecto.
Adición de complejidad es un buen criterio siempre que sea medible y lo expreses como algo medible. ¿Hay algún gestor que se incluya de una forma más compleja que apt-get lo que sea o copiar un binario?

2024-12-10 06:55 UTC, JJ commented on docs/gestor_tareas.md
> +1. Activa y mantenida, gracias a su integración directa en Go.
¿Qué es "integración directa en Go"?

2024-12-10 15:45 UTC, Mario25402 commented on docs/gestor_dependencias.md
> +## Configuración manual
https://github.com/Mario25402/AskETSIIT/commit/76c5712043084ec5358d019890f314f4bef5e976

2024-12-10 15:48 UTC, Mario25402 commented on docs/gestor_tareas.md
> +1. Activa y mantenida, gracias a su integración directa en Go.
Me refiero a que el archivo de configuración `magefile` se escribe en Go

2024-12-10 16:33 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Madurez y robustez:** El nivel de desarrollo de la herramienta debe ser suficiente y debe seguir teniendo mantenimiento frecuente para maximizar la compatibilidad con el lenguaje y minimizar los
Quizás "robustez" no era la palabra que mejor lo definía. Es un mismo criterio ya que ambos están ligados de manera que una herramienta madura conforme progresa con sus actualizaciones. https://github.com/Mario25402/AskETSIIT/commit/0e171d0111ef56c214a3b9f73d1cab7d417cbb49

2024-12-10 16:35 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Adición de complejidad:** Se valorará la simplicidad de inclusión y uso del gestor, de manera que no aumente la dificultad del proyecto.
No es tanto a la instalación, ya que como bien dices, la mayoría es ejecutar un comando. Sino que se enfoca más en el uso y la adaptación del desarrollador a la herramienta. https://github.com/Mario25402/AskETSIIT/commit/0e171d0111ef56c214a3b9f73d1cab7d417cbb49

2024-12-10 17:14 UTC, Mario25402 commented on Taskfile.yml
> +      - go fmt ./...
Con la opción -e mostraremos los errores de sintaxis. https://github.com/Mario25402/AskETSIIT/commit/b7db9c2fa90ce6bb157d2aec0e5fad8d1a5cddc0

2024-12-10 17:16 UTC, Mario25402 commented
@JJ

2024-12-12 08:37 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Adición de complejidad:** Se valorará que la curva de aprendizaje de la herramienta sea simple o menor que las demás.
Se presupone que estamos en igualdad de condiciones porque desde esa perspectiva, elegiriamos la herramienta con la que ya estamos familiarizados. Objetivamente y a simple vista viendo ejemplos, hay ficheros de configuración más simples que otros, o al menos que se entienden más fácilmente. https://github.com/Mario25402/AskETSIIT/commit/e4aaf5840e43e55fb614d2c13a829720637b9d64

2024-12-12 08:38 UTC, Mario25402 commented
@JJ

2024-12-12 09:03 UTC, JJ requested changes
Dale una vuelta, por favor.

2024-12-12 09:03 UTC, JJ commented on docs/gestor_tareas.md
> +- **Compresión:** Se valorará que la sintaxis sea entendible y clara.
¿Esto es objetivo?

2024-12-12 09:11 UTC, Mario25402 commented
@JJ

2024-12-12 12:01 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Compresión:** Se valorará que la sintaxis sea entendible y clara.
Disculpa, fallo mio al escribir el comentario.

2024-12-13 07:02 UTC, JJ requested changes
A partir del cuarto o quinto objetivo aprobado, es bastante cuestionable que se pongan las herramientas que ha puesto todo el mundo y además con criterios confusos y agrupados. En el objetivo se busca que sepáis buscar herramientas, aunque no sean las más populares.

2024-12-13 07:02 UTC, JJ commented on docs/gestor_tareas.md
> +## Conclusión
¿Sería posible que no os limitárais a las 4 herramientas que *ha puesto todo el mundo*? Por favor, buscad un poco más, que hay.

2024-12-13 07:02 UTC, JJ commented on docs/gestor_tareas.md
> +- **Task**: Gracias a la simple configuración con *YAML* consideramos ésta como nuestra elección.
Este no es un criterio, ni de hecho es objetivo. Si te gusta más porque ya la ha elegido todo el mundo, dilo así.

2024-12-13 07:09 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Task**: Gracias a la simple configuración con *YAML* consideramos ésta como nuestra elección.
Te equivocas, yo no se ni las herramientas que ha utilizado la gente ni lo que ha elegido porque los repositorios son privados y llevo ya un tiempo con ellos elegidos, ayer en clase concluimos que bien todas las herramientas puedes ser válidas y al final la elección no por cuestiones de peso.

2024-12-13 07:36 UTC, JJ commented on docs/gestor_tareas.md
> +- **Task**: Gracias a la simple configuración con *YAML* consideramos ésta como nuestra elección.
No me equivoco: es la que ha elegido todo el mundo. Nadie ha elegido `just`. Si dices que la has elegido porque usa YAML, estás mencionando un criterio, lo quieras o no. Y si dices que es por la "configuración simple" también es un criterio, lo quieras o no. Un criterio que *no* es objetivo. Meter criterios de rondón en la "justificación" de la elección es tan malo como ponerlo arriba, o peor si es para justificar elegir lo que ya ha elegido todo el mundo (o casi todos)

2024-12-13 07:45 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Task**: Gracias a la simple configuración con *YAML* consideramos ésta como nuestra elección.
Pues te aclaro que mi predilección a elegirlo no ha sido eso porque básicamente no sé lo que han escogido mis compañeros.

El resto, oído, lo corregiré.

2024-12-13 10:51 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Madurez y progreso:** El nivel de desarrollo de la herramienta debe ser suficiente y debe seguir teniendo mantenimiento frecuente para maximizar la compatibilidad con el lenguaje y minimizar los
https://github.com/Mario25402/AskETSIIT/commit/7e2ba0651f8c31bb3980de87372803b659dc31b1

2024-12-13 11:23 UTC, Mario25402 commented on docs/gestor_tareas.md
> +## Conclusión
https://github.com/Mario25402/AskETSIIT/commit/049e1956f97fe6922011cfba80f5ce11d130f8e8

2024-12-13 13:00 UTC, Mario25402 commented
@JJ

2024-12-13 16:33 UTC, JJ requested changes
Por favor, asegúrate que las herramientas que incluyes son de verdad lo que dicen ser.

2024-12-13 16:33 UTC, JJ commented on docs/gestor_tareas.md
> +[Dagger](https://dagger.io/) es una herramienta diseñada para simplificar y unificar flujos de trabajo CI/CD y tareas automatizadas en proyectos de software
¿Has intentado escribir un fichero de tareas con esto? ¿Qué te ha salido?

2024-12-13 16:33 UTC, JJ commented on docs/gestor_tareas.md
> +- Proyecto no tan completo como otras opciones.
¿No es tan completo por qué?
¿Esto es un criterio? ¿La "completitud"?

2024-12-16 09:00 UTC, JLombar reviewed
Buenas Mario hay bastantes cosas bien y llevas buen camino pero faltan algunos detallitos más a parte de los que te ha comentado ya Juan. Recuerda siempre intentar poner algo medible como requisito y **dónde** lo podemos medir para ver que realmente es cierto.  Como consejillo te puedo decir que si algo es medible es ciertamente objetivo, por si te sirve de algo.

Si quieres cuando termines de cambiarlo pídeme revisión y le damos otro repasillo😛

2024-12-16 09:00 UTC, JLombar commented on README.md
> +## Gestor de tareas
Al igual que haces con el resto de objetivos podrías enlazar al README los documentos en los que hablas de ello

2024-12-16 09:00 UTC, JLombar commented on justfile
> +install-deps:
No tienes un target en el justfile que sea sólo install, puedes eliminar el "-deps", no aporta mucho.

2024-12-16 09:00 UTC, JLombar commented on docs/gestor_tareas.md
> +- Último *release* hace más de un año, *commits* con frecuencia media.
Podrías añadir el GitHub de la herramienta si vas ha hablar de los commits, o incluso decir en los requisitos que vas a comprobarlo revisando el repositorio del gestor

2024-12-16 09:00 UTC, JLombar commented on docs/gestor_dependencias.md
> +El gestor oficial de los desarrolladores del lenguaje, nacido en la versión 1.11 y obligatorio desde la versión 1.16.
De donde sacas esto? Es interesante añadir la documentación de la herramienta (o de lo que sea que estemos hablando en  el momento) para que todo quede más completo y claro

2024-12-20 11:46 UTC, Mario25402 commented on README.md
> +## Gestor de tareas
https://github.com/Mario25402/AskETSIIT/commit/40d1101b7a23b4e633a886eb7705a19312086117

2024-12-20 11:52 UTC, Mario25402 commented on docs/gestor_dependencias.md
> +El gestor oficial de los desarrolladores del lenguaje, nacido en la versión 1.11 y obligatorio desde la versión 1.16.
https://github.com/Mario25402/AskETSIIT/commit/3c53ecae7ebded6a6344cf5be0cabcc9f827053c

2024-12-20 12:02 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- Último *release* hace más de un año, *commits* con frecuencia media.
https://github.com/Mario25402/AskETSIIT/commit/54b0b39476be0213f8e38a47578b6f9ba885ab0d

2024-12-20 12:07 UTC, Mario25402 commented on docs/gestor_tareas.md
> +[Dagger](https://dagger.io/) es una herramienta diseñada para simplificar y unificar flujos de trabajo CI/CD y tareas automatizadas en proyectos de software
Como comento en las conclusiones, se descarta esta herramienta porque es necesario tener `docker` para poder usarla, lo que añadiría dificultad innecesaria al proyecto.

2024-12-21 17:44 UTC, Mario25402 commented
@JJ

2024-12-22 18:45 UTC, JJ commented
¿Seguro que no quieres pedirle revisión a @JLombar antes?

2024-12-23 08:26 UTC, JLombar reviewed
Ya sé que no me has mencionado pero ya que lo hace Juan pues te digo el par de cambios que creo que tienes que modificar. Ánimo que son 2 tonterías que se hacen en un rato, hazlo cuanto antes

2024-12-23 08:26 UTC, JLombar commented on docs/gestor_tareas.md
> +- El repositorio de GitHub de cada herramienta será revisado individualmente con el fin de ver el nivel/ritmo de desarollo.
Estas 2 líneas son el mismo requisito, podrías ponerlas juntas.

2024-12-23 08:26 UTC, JLombar commented on docs/gestor_tareas.md
> +- El repositorio de GitHub de cada herramienta será revisado individualmente con el fin de ver el nivel/ritmo de desarollo.
Por otro lado no creo que progreso sea un nombre adecuado adecuado, ya que hablas de mantenimiento ponle eso, mantenimiento, ¿no? Por otro lado creo que deberías intentar informarte un poco más el por qué tener en cuenta el mantenimiento a la hora de justificarlo como requisito (busca deuda técnica si no sabes de lo que te hablo e infórmate). 

Creo que la explicación es muy mejorable ya que hay más cosas que mencionar a la hora de elegir el mantenimiento. Ya que lo vas a poner como único requisito asegurate de que esté bien al 100% y completo.

2024-12-23 08:26 UTC, JLombar commented on docs/gestor_tareas.md
> +- El repositorio de GitHub de cada herramienta será revisado individualmente con el fin de ver el nivel/ritmo de desarollo.
Por último sobre
> El repositorio de GitHub de cada herramienta será revisado individualmente con el fin de ver el nivel/ritmo de desarollo.

Entiendo a lo que te refieres pero realmente vas a mirar el nivel de ritmo/desarrollo mirando los 3 últimos commits?  Es lo que hemos hecho todos no hay nada malo con ello, pero si va a ser así pues simplemente dí que verás la fecha del último commit, o la frecuencia de los mismo o algo así, pero algo que sea lo que realmente vas a hacer para que tenga sentido luego a la hora de hablar de las herramientas

2024-12-23 17:15 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- El repositorio de GitHub de cada herramienta será revisado individualmente con el fin de ver el nivel/ritmo de desarollo.
Perdona @JLombar, imaginaba que no seguirías revisando, muchas gracias por tus comentarios y consejos. Aquí tienes la correción para que le eches un vistazo cuando puedas !! bd716192618829059d8d90cc5ebfbfab5720b291

2024-12-24 08:54 UTC, JLombar approved these changes
@Mario25402 En mi opinión está bien, si las herramientas son lo que dices que son (yo no lo he mirado) por mi parte está aprobado

2024-12-24 08:58 UTC, Mario25402 commented
@JJ

2024-12-30 11:02 UTC, JJ requested changes
Por favor, usad criterios *verdaderamente* objetivos.

2024-12-30 11:02 UTC, JJ commented on docs/gestor_tareas.md
> +Vistas diferentes alternativas para nuestra elección como gestor de tareas, podemos concluir diciendo que no escogeremos `XC` porque su mantenimiento es bajo, al igual que el de `Taskrunner`.
¿Qué significa "mantenimiento bajo"? Tienes commits de hace tres meses.

2024-12-30 11:02 UTC, JJ commented on docs/gestor_tareas.md
> +- Sin *releases* oficiales, sin [*commits*](https://github.com/joerdav/xc) desde hace un año.
El enlace es incorrecto. Y ya puestos, podías enlazar la historia de commits, no otra vez el mismo enlace.

2024-12-30 17:23 UTC, Mario25402 commented on README.md
> +El fichero que contiene la declaración de "Clase" será el que implemente la lógica de negocio ya que sobre él recae el procesamiento principal del proyecto.
Viene por la interpretación del siguiente parrafo del [guión](https://jj.github.io/IV/documentos/proyecto/3.Automatizar):

> La descripción del proyecto tiene que seguir progresando, así que el README.md tiene que incluir una descripción real de la clase que se vaya a comprobar y qué uso va a tener dentro del servicio (o servicios) web que se van a desplegar más adelante.

2024-12-30 17:33 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- Sin *releases* oficiales, sin [*commits*](https://github.com/joerdav/xc) desde hace un año.
Corregido en be22d1ed84516094ec79436ae66f9d345fd586c1

2024-12-30 17:42 UTC, Mario25402 commented on docs/gestor_tareas.md
> +  - El repositorio de GitHub de cada una será visitado individualmente, revisando la frecuencia y fechas de los últimos commits y versiones.
Este cambio está sugerido por mi compañero jorge, que mencionaba que dijera exactamente qué iba a hacer con esos commits. La "frecuencia de últimos commits" nos fijamos en que el proyecto no esté abandonado, que tenga siga teniendo desarrollo.

2024-12-30 18:56 UTC, Mario25402 commented on docs/gestor_tareas.md
> +Vistas diferentes alternativas para nuestra elección como gestor de tareas, podemos concluir diciendo que no escogeremos `XC` porque su mantenimiento es bajo, al igual que el de `Taskrunner`.
Bajo en comparación con el resto

2024-12-30 19:02 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
Es dificil aplicar criterios objetivos cuando la tarea que vamos a realizar es común y prácticamente todas las opciones que evaluemos podrán cumplirlas, nos limitamos a comparar que desarrollo tiene más interactividad con la comunidad que al fin y al cabo son las personas que *testean* el producto final. Datos objetivos como vulnerabilidades quedan incompletos debido al desconocimiento de las herramientas.

[Aquí](f71c7ee6617eed90599305790080acf6d051582e) intento aclararlo un poco mejor pero, principalmente es lo que expongo en el texto superior.

2024-12-30 19:03 UTC, Mario25402 commented
Cuando te sea posible contestarme @JJ, necesito ir avanzando.

2024-12-31 08:17 UTC, JJ commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
Tomar decisiones es esencial en ingeniería, y si no se pueden aplicar criterios objetivos es que no se sabe como hacerlo. En [el guión](https://jj.github.io/IV/documentos/proyecto/3.Automatizar) comenta que se tienen que usar:
> Criterios objetivos adicionales: sobre todo, seguridad, prestaciones o algo que se pueda reducir a la cantidad de tiempo que se va a invertir en mantener lo relacionado con la decisión. La mayoría de las herramientas tendrán benchmarks que las comparen con otras; pero siempre se puede intentar hacer pruebas sobre el propio proyecto. 

Si no sabes establecer estos criterios objetivos podemos dar este objetivo por no pasado y comenzar con el siguiente.

2024-12-31 08:18 UTC, JJ commented on docs/gestor_tareas.md
> +  - El repositorio de GitHub de cada una será visitado individualmente, revisando la frecuencia y fechas de los últimos commits y versiones.
"Nos fijamos en" no es una definición. Y te recuerdo que los comentarios lo que indican es un problema que hay que solucionar haciendo cambios, no contestando.

2024-12-31 08:19 UTC, JJ commented on docs/gestor_tareas.md
> +Vistas diferentes alternativas para nuestra elección como gestor de tareas, podemos concluir diciendo que no escogeremos `XC` porque su mantenimiento es bajo, al igual que el de `Taskrunner`.
De veras, si no entiendes que los comentarios son problemas que hay que solucionar cambiando y no contestando no creo que merezca la pena seguir haciendo estos comentarios. Entiende un "está mal" genérico y haz lo que estimes conveniente.

2024-12-31 08:20 UTC, JJ commented
> Cuando te sea posible contestarme @JJ, necesito ir avanzando.

Los comentarios a los PRs no son comienzos de una conversación, son problemas que hay que resolver. Esto es algo básico en la asignatura, en este objetivo y en el resto. Por favor, soluciónalos y cuando lo hayas hecho pide revisión. Si tienes alguna duda pregunta, preferiblemente en el grupo de Telegram.

2024-12-31 09:46 UTC, Mario25402 commented on docs/gestor_tareas.md
> +Vistas diferentes alternativas para nuestra elección como gestor de tareas, podemos concluir diciendo que no escogeremos `XC` porque su mantenimiento es bajo, al igual que el de `Taskrunner`.
Esta añadido la adición del comentario en el último commit, error mio por no comentarlo: f71c7ee6617eed90599305790080acf6d051582e

2024-12-31 10:02 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
Después de un mes pidiendo revisiones no creo que abandonar el objetivo sea la mejor opción porque básicamente he perdido el tiempo, a este ritmo ya tengo claro que al objetivo 5 no voy a llegar. 

En las primeras versiones tenía como criterios a lo que haces referencia del guión, en clase me dijiste que eran invalidos porque no tenemos forma objetiva de medirlos, para la seguridad podemos usar bases de datos de vulnerabilidades (en donde la mayoria de las opciones no tenemos datos porque no figuran registros), prestaciones se pueden medir con benchmarking donde nos pasa igual, no hay registros, y si los hay no son justos porque no miden lo mismo. Lo vamos aplicar a una tarea del proyecto, las diferencias serán mínimas pero al menos son medibles.

2024-12-31 10:08 UTC, Mario25402 commented on docs/gestor_tareas.md
> +  - El repositorio de GitHub de cada una será visitado individualmente, revisando la frecuencia y fechas de los últimos commits y versiones.
Entiendo que los comentarios son problemas que hay que resolver y la gran mayoría de ellos los realizo, así puedes verlo en el resto del PR, pero si las revisiones de mis compañeros concluyen en una cosa y las tuyas en otra diferente creo conveniente "explicarte" el por qué de la pregunta. De igual manera haré el cambio.

2025-01-02 11:10 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
8152e26b8e5162def44ecc14946ef12b80396758

2025-01-02 11:11 UTC, Mario25402 commented on docs/gestor_tareas.md
> +  - El repositorio de GitHub de cada una será visitado individualmente, revisando la frecuencia y fechas de los últimos commits y versiones.
8152e26b8e5162def44ecc14946ef12b80396758

2025-01-02 11:11 UTC, Mario25402 commented
@JJ

2025-01-03 11:17 UTC, JJ requested changes
Se considera positivamente que hayas escogido un criterio objetivo como las prestaciones, pero habría sido conveniente que enlazaras los commits donde has creado ese fichero y probado esas prestaciones o simplemente dejar todos los ficheros que has usado para probar en el PR, así como las capturas de pantallas.
Por otro lado, no es muy positivo que una vez establecido el criterio objetivo no lo apliques, y que dejes criterios que no lo son.

2025-01-03 11:17 UTC, JJ commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
¿De qué forma ese cambio resuelve el problema con *este* criterio que propones?

2025-01-03 11:17 UTC, JJ commented on docs/gestor_tareas.md
> +- *Factores convenientes:*
???

2025-01-03 11:17 UTC, JJ commented on docs/gestor_tareas.md
> +    - Mayores prestaciones, medido con el tiempo de ejecución de la misma tarea.
¿Esto es repetición de la de arriba?

2025-01-03 11:17 UTC, JJ commented on docs/gestor_tareas.md
> +La mayoría de opciones son poco conocidas y no hay registro de vulnerabilidades en [páginas especializadas](https://www.cvedetails.com/), para las que sí hay, son pocas, en antiguas versiones o funci
Ya expliqué en clase (repetidamente) que si hubiera vulnerabilidades sería a través de las dependencias. Un gestor de tareas de por sí no puede introducir ninguna. ¿De qué manera `make` puede introducir una vulnerabilidad en tu proyecto?

2025-01-03 11:17 UTC, JJ commented on docs/gestor_tareas.md
> +Por último entre `Make` y `Just`, que son los dos que mejores tiempos consiguen, elegiremos **Just**.
¿Tienes un criterio objetivo como son las prestaciones, y lo tiras a la basura escogiendo el segundo mejor?

2025-01-03 11:47 UTC, Mario25402 commented on docs/gestor_tareas.md
> +Por último entre `Make` y `Just`, que son los dos que mejores tiempos consiguen, elegiremos **Just**.
Dejé *Just* por variar un poco las elecciones y no trabajar con las mismas herramientas siempre, aunque es indiferente. https://github.com/Mario25402/AskETSIIT/commit/9fa760ae50169c2ac21b4c8738362aede34fca8a

2025-01-03 11:51 UTC, Mario25402 commented on docs/gestor_tareas.md
> +La mayoría de opciones son poco conocidas y no hay registro de vulnerabilidades en [páginas especializadas](https://www.cvedetails.com/), para las que sí hay, son pocas, en antiguas versiones o funci
Si ese es el caso, eliminaremos las menciones sobre seguridad ya que se encuentran en igualdad de condiciones y es innecesario: https://github.com/Mario25402/AskETSIIT/commit/43a48091c1be68669ec6c5c3295965ff84c2c558

De las pocas vulnerabilidades registradas, la única sobre *make* es [ésta](https://www.cvedetails.com/cve/CVE-2000-0151/).

2025-01-03 11:52 UTC, Mario25402 commented on docs/gestor_tareas.md
> +    - Mayores prestaciones, medido con el tiempo de ejecución de la misma tarea.
https://github.com/Mario25402/AskETSIIT/commit/d5304c6a13e35800f0ceb4607538006512d2ae0a

2025-01-03 11:52 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- *Factores convenientes:*
https://github.com/Mario25402/AskETSIIT/commit/d5304c6a13e35800f0ceb4607538006512d2ae0a

2025-01-03 12:02 UTC, Mario25402 commented on docs/gestor_tareas.md
> +- **Mantenimiento:** Un mantenimiento adecuado es importarte a nivel de seguridad para proteger el entorno de desarrollo ya que los gestores de tareas ejecutan comandos y pueden ser objetivos para bú
Cierto, me liaría con los commits. en resumen: https://github.com/Mario25402/AskETSIIT/commit/4f17904b549f4468e99ecc92d3375f7c07622ee4

2025-01-03 12:11 UTC, Mario25402 commented on docs/gestor_tareas.md
> +Por último entre `Make` y `Just`, que son los dos que mejores tiempos consiguen, elegiremos **Just**.
https://github.com/Mario25402/AskETSIIT/pull/24/commits/831644af7f48c4ccbf5ac610ff12881c253c0aea
https://github.com/Mario25402/AskETSIIT/pull/24/commits/67d5833fc71fec477e24d4498a73f91026d039c7

2025-01-03 12:33 UTC, Mario25402 commented
@JJ, he añadido los archivos con los que he probado y una captura de los resultados, la variación de tiempo es debido a que he cambiado los archivos de localización, antes se hacia en el mismo directorio, lo cuál disminuía el tiempo. https://github.com/Mario25402/AskETSIIT/commit/3fcc3bd7ab3148d6ed7170d537cf71520652c738

2025-01-05 08:01 UTC, JJ approved these changes
:+1: Los ficheros que sean solo para evaluación puedes eliminarlos antes del siguiente PR.
Y por favor, mirad qué significan los tres tiempos que da `time`

2025-01-05 15:58 UTC, merged